src/main/java/rpo/bean/EmployeeBean.java
package rpo.bean;

import javax.validation.Valid;
import org.springframework.web.multipart.MultipartFile;
import rpo.model.Employee;

/**
 *
 * @author Patrick Tan (patricktan2014@yahoo.com)
 */
public class EmployeeBean {

    @Valid
    private Employee employee;
    private MultipartFile securityLicenseUpload;
    private MultipartFile firstAidLicenseUpload;

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public MultipartFile getSecurityLicenseUpload() {
        return securityLicenseUpload;
    }

    public void setSecurityLicenseUpload(MultipartFile securityLicenseUpload) {
        this.securityLicenseUpload = securityLicenseUpload;
    }

    public MultipartFile getFirstAidLicenseUpload() {
        return firstAidLicenseUpload;
    }

    public void setFirstAidLicenseUpload(MultipartFile firstAidLicenseUpload) {
        this.firstAidLicenseUpload = firstAidLicenseUpload;
    }
}

src/main/java/rpo/model/EmployeeLog.java
package rpo.model;
// Generated May 2, 2015 10:00:50 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
import rpo.constant.AppConstant;
import rpo.enums.LogStatusEnum;
import rpo.utility.AppUtility;

/**
 * EmployeeLog generated by hbm2java
 */
@Entity
@Table(name = "employee_log")
@AttributeOverride(name = "primaryId", column = @Column(name = "log_id"))
public class EmployeeLog extends BaseModel {

    @NotNull
    private Employee employee;
    @JsonFormat(pattern = AppConstant.DEFAULT_DATE_TIME_FORMAT, shape = JsonFormat.Shape.STRING)
    @NotNull
    private Date startDatetime;
    @JsonFormat(pattern = AppConstant.DEFAULT_DATE_TIME_FORMAT, shape = JsonFormat.Shape.STRING)
    @NotNull
    private Date endDatetime;
    @NotEmpty
    private String company;
    @NotEmpty
    private String location;
    private String logStatus;
    private String remarks;
    @JsonFormat(pattern = AppConstant.DEFAULT_DATE_TIME_FORMAT, shape = JsonFormat.Shape.STRING)
    private Date paidDatetime;

    public EmployeeLog() {
    }

    public EmployeeLog(Employee employee, Date startDatetime) {
        this.employee = employee;
        this.startDatetime = startDatetime;
    }

    public EmployeeLog(Employee employee, Date startDatetime, Date endDatetime, String remarks) {
        this.employee = employee;
        this.startDatetime = startDatetime;
        this.endDatetime = endDatetime;
        this.remarks = remarks;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_id", nullable = false)
    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_datetime", nullable = false, length = 19)
    public Date getStartDatetime() {
        return this.startDatetime;
    }

    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_datetime", length = 19)
    public Date getEndDatetime() {
        return this.endDatetime;
    }

    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    @Column(name = "company", nullable = false, length = 100)
    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    @Column(name = "location", nullable = false, length = 100)
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name = "remarks", length = 200)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "log_status", length = 2)
    public String getLogStatus() {
        return this.logStatus;
    }

    public void setLogStatus(String logStatus) {
        this.logStatus = logStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "paid_datetime", length = 19)
    public Date getPaidDatetime() {
        return paidDatetime;
    }

    public void setPaidDatetime(Date paidDatetime) {
        this.paidDatetime = paidDatetime;
    }

    @Transient
    public String getStrLogStatus() {
        return LogStatusEnum.getLabel(logStatus);
    }

    @Transient
    public String getTotalHours() {
        return AppUtility.calculateDiff(startDatetime, endDatetime);
    }

    public static void main(String[] args) {
        Calendar start = Calendar.getInstance();
        start.set(Calendar.HOUR_OF_DAY, 10);
        start.set(Calendar.MINUTE, 15);

        EmployeeLog log = new EmployeeLog();
        log.setStartDatetime(start.getTime());
        log.setEndDatetime(new Date());

        System.out.println(" ... " + log.getTotalHours());
    }
}

src/main/java/rpo/controller/EmployeeController.java
package rpo.controller;

import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.Set;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.ValidatorFactory;
import javax.validation.groups.Default;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.ServletRequestDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import rpo.bean.EmployeeBean;
import rpo.bean.PropertyEditorBean;
import rpo.bean.ResponseBean;
import rpo.exception.CustomException;
import rpo.model.Employee;
import rpo.model.EmployeeLog;
import rpo.model.SecUser;
import rpo.service.EmployeeLogService;
import rpo.service.EmployeeService;
import rpo.utility.MessageUtil;
import rpo.utility.SecurityUtility;

/**
 *
 * @author Patrick Tan (patricktan2014@yahoo.com)
 */
@Controller
@RequestMapping("/secured/employee/*")
public class EmployeeController {

    private static final Logger LOGGER = Logger.getLogger(EmployeeController.class);
    @Autowired
    private EmployeeService employeeService;
    @Autowired
    private EmployeeLogService employeeLogService;

    @InitBinder
    protected void initBinder(HttpServletRequest request, ServletRequestDataBinder binder) throws Exception {
        LOGGER.info("init binder param: " + request.getParameter("employee"));

        if (!StringUtils.isEmpty(request.getParameter("employee"))) {
            PropertyEditorBean bean = new PropertyEditorBean(Employee.class);
            binder.registerCustomEditor(Employee.class, "employee", bean);
        }
    }

    @RequestMapping("add")
    public String add(ModelMap model, @RequestParam(required = false, value = "mode") String mode) {
        Employee employee = new Employee();

        if ("test".equals(mode)) {

            int random = new Random().nextInt();

            employee.setLastName("last_" + random);
            employee.setFirstName("first_" + random);
            employee.setContactNo("contact_" + random);
            employee.setAddress("address_" + random);

            employee.setFirstAidLicenseExpiry(new Date());
            employee.setFirstAidLicenseNo("first_" + random);

            employee.setSecurityLicenseExpiry(new Date());
            employee.setSecurityLicenseNo("sec_" + random);

            SecUser secUser = new SecUser("user" + random);
            secUser.setConfirmPassword("123456");
            secUser.setEnteredPassword("123456");
            employee.setEmployeeUsername(secUser);
        }

        model.addAttribute("employee", employee);
        return "manageEmployee";
    }

    @RequestMapping(value = "delete/{encryptedKey}")
    @ResponseBody
    public ResponseBean delete(@PathVariable String encryptedKey) {
        ResponseBean responseBean = new ResponseBean();

        try {
            employeeService.tagAsDeleted(encryptedKey);
            responseBean.setMessage(MessageUtil.RECORD_DELETED);
        } catch (CustomException e) {
            responseBean.setMessage(e.getMessage());
        }

        return responseBean;
    }

    @RequestMapping("log")
    public String log(ModelMap model) {
        model.addAttribute("employee", employeeService.findByUsername(SecurityUtility.getCurrentUsername()));
        return "logHours";
    }

    @RequestMapping(value = "log/{actionType}")
    @ResponseBody
    public ResponseBean processLog(HttpServletRequest request, @PathVariable String actionType) {
        String encryptedKey = request.getParameter("log");

        if (null != actionType) {
            switch (actionType) {
                case "cancel":
                    employeeLogService.cancelLog(encryptedKey);
                    break;
                case "pay":
                    employeeLogService.payLog(encryptedKey);
                    break;
                case "delete":
                    employeeLogService.deleteLog(encryptedKey);
                    break;
            }
        }

        ResponseBean responseBean = new ResponseBean();
        responseBean.getData().put("logs",
                employeeLogService.filterLogs(request.getParameter("employee"),
                        request.getParameter("filter")));

        return responseBean;
    }

    @RequestMapping(value = "save", method = RequestMethod.POST)
    @ResponseBody
    public ResponseBean save(@ModelAttribute("data") EmployeeBean employeeBean) {
        ResponseBean responseBean = new ResponseBean();

        Employee employee = employeeBean.getEmployee();

        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Set<ConstraintViolation<Employee>> errors = factory.getValidator().validate(employee, Default.class);

        List<FieldError> fieldErrors = null;

        boolean isPasswordValid = employee.getEmployeeUsername().isValid();

        if (!isPasswordValid) {
            fieldErrors = new ArrayList<>();
            fieldErrors.add(new FieldError("employee", "employeeUsername.enteredPassword", "the password entered did not matched."));
        }

        if (!CollectionUtils.isEmpty(errors)) {

            for (ConstraintViolation<Employee> e : errors) {
                if ("employeeUsername.enteredPassword".equals(e.getPropertyPath().toString()) && isPasswordValid) {
                    continue;
                }

                if (fieldErrors == null) {
                    fieldErrors = new ArrayList<>();
                }

                fieldErrors.add(new FieldError("employee", e.getPropertyPath().toString(), e.getMessage()));
            }
        }

        responseBean.setErrors(fieldErrors);

        if (CollectionUtils.isEmpty(responseBean.getErrors())) {
            try {
                Employee oldEmployee = employeeService.findById(employee.getPrimaryId());

                if (employeeBean.getSecurityLicenseUpload() != null) {
                    employee.setSecurityLicenseFile(employeeBean.getSecurityLicenseUpload().getBytes());
                    employee.setSecurityLicenseFileType(employeeBean.getSecurityLicenseUpload().getContentType());
                } else if (oldEmployee != null) {
                    employee.setSecurityLicenseFile(oldEmployee.getSecurityLicenseFile());
                    employee.setSecurityLicenseFileType(oldEmployee.getSecurityLicenseFileType());
                }

                if (employeeBean.getFirstAidLicenseUpload() != null) {
                    employee.setFirstAidLicenseFile(employeeBean.getFirstAidLicenseUpload().getBytes());
                    employee.setFirstAidLicenseFileType(employeeBean.getFirstAidLicenseUpload().getContentType());
                } else if (oldEmployee != null) {
                    employee.setFirstAidLicenseFile(oldEmployee.getFirstAidLicenseFile());
                    employee.setFirstAidLicenseFileType(oldEmployee.getFirstAidLicenseFileType());
                }
            } catch (IOException ex) {
                LOGGER.error(ex);
            }

            employeeService.saveOrUpdate(employee);

            responseBean.getData().put("encryptedKey", employee.getEncryptedKey());
            responseBean.getData().put("createdBy", employee.getCreatedBy());
            responseBean.getData().put("createdDate", employee.getCreatedDate());

            if (employee.getUpdatedBy() == null) {
                responseBean.setMessage(MessageUtil.RECORD_ADDED);
            } else {
                responseBean.setMessage(MessageUtil.RECORD_UPDATED);
            }
        }

        return responseBean;
    }

    @RequestMapping(value = "save/log", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
    @ResponseBody
    public ResponseBean saveLog(@RequestBody @Validated EmployeeLog entity, BindingResult binding) {
        ResponseBean responseBean = new ResponseBean();

        if (!binding.hasErrors()) {
            employeeLogService.saveOrUpdate(entity);

            responseBean.getData().put("logs",
                    employeeLogService.filterLogs(entity.getEmployee().getEncryptedKey(), null));
        } else {
            responseBean.setErrors(binding.getFieldErrors());
        }

        return responseBean;
    }

    @RequestMapping("view/{id}")
    public String view(ModelMap model, @PathVariable String id) {
        Integer primaryId = SecurityUtility.decryptId(id);

        if ("all".equalsIgnoreCase(id)) {
            return "viewEmployees";
        } else if (primaryId > 0) {
            model.addAttribute("employee", employeeService.findById(primaryId));
            return "manageEmployee";
        } else {
            return "redirect:/secured/employee/view/all";
        }
    }

    @RequestMapping(value = "view/attachment/{type}/{key}")
    public void viewAttachment(@PathVariable(value = "type") String attachmentType,
            @PathVariable(value = "key") String encryptedKey,

src/main/webapp/WEB-INF/pages/secured/employee/manage.jsp
<%@include file="../../common/taglibs.jsp" %>

<div ng-app="employeeModule">
    <div  class="row" ng-controller="manageCtrl">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-5">
            <div class="panel panel-primary">
                <div class="panel-heading">EMPLOYEE INFORMATION</div>
                <div class="panel-body">    
                    <form method="post" enctype="multipart/form-data" ng-submit="save()" novalidate>
                        <%@include file="../../common/employee-info.jsp" %>
                        <hr>
                        <div class="row">
                            <div class="col-md-12 text-right">
                                <button class="btn btn-success btn-sm" type="submit">SUBMIT</button>
                                |
                                <button class="btn btn-danger btn-sm">
                                    <a href="${baseUrl}/secured/employee/view/all">BACK</a>
                                </button>
                            </div>
                        </div>    
                    </form>
                </div>
            </div>
        </div>
        <c:if test="${not empty requestScope.employee.encryptedKey}">
            <div class="col-xs-12 col-sm-7 col-md-5 col-lg-7">
                <%@include file="view-log-hours.jsp" %>
            </div>
        </c:if>
    </div>
</div>

src/main/webapp/WEB-INF/pages/secured/employee/view-log-hours.jsp
<%@include file="../../common/taglibs.jsp" %>

<div ng-controller="viewLogHoursCtrl">
    <input type="hidden" 
           class="form-control " 
           ng-model="employee.encryptedKey"    
           ng-init="employee.encryptedKey = '${requestScope.employee.encryptedKey}'"
           />

    <div class="panel panel-primary" ng-init="initLogs()">
        <div class="panel-heading">
            LOGGED HOURS  

            <div class="btn-group">

                <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">                    
                    <span ng-show="filterBy" class="ng-hide">{{filterBy.label}}</span>  <span class="caret" ng-click="filter()"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a ng-click="filter({id: 'all', label: 'All'})">All</a>
                    </li>
                    <li>
                        <a ng-click="filter({id: 'today', label: 'Today'})">Today</a>
                    </li>
                    <li>
                        <a ng-click="filter({id: 'this-week', label: 'This Week'})">This Week</a>
                    </li>
                    <li>
                        <a ng-click="filter({id: 'last-week', label: 'Last Week'})">Last Week</a>
                    </li>
                    <li>
                        <a ng-click="filter({id: 'this-month', label: 'This Month'})">This Month</a>
                    </li>
                    <li>
                        <a ng-click="filter({id: 'last-month', label: 'Last Month'})">Last Month</a>
                    </li>
                    <li>
                        <a ng-click="filter({id: 'last-6-months', label: 'Last 6 Months'})">Last 6 Months</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="panel-body">
            <div class="row" style="">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <div class="alert alert-warning ng-hide" ng-show="!showLoading && (!items.length || items.length === 0)">
                        <p style="margin-bottom: 0px; font-size: 13px">
                            <span class="glyphicon glyphicon-exclamation-sign"></span> No record/s found.
                        </p>
                    </div>

                    <div class="alert alert-success" ng-show="showLoading" style="background-color: white">
                        <p style="margin-bottom: 0px; font-size: 13px" class="text-success">
                            Please wait, retrieving records <img src="${baseUrl}/resources/img/loader.gif" />
                        </p>
                    </div>
                    <div class="ng-hide" ng-show="items.length > 0" >

                        <div style="height: 70vh; overflow: auto; padding-right: 2px">
                            <div>
                                <table id="tblLogHours" class="table table-condensed table-hover scroll">                                   
                                    <tbody>
                                        <tr ng-repeat="log in items">

                                            <security:authorize access="hasAnyRole('ROLE_ADMIN', 'ROLE_SUPER_ADMIN')">
                                                <td class="text-center" style="width: 10%; vertical-align: middle">                                                    
                                                    <span ng-show="log.logStatus == 'U'">
                                                        <input type="checkbox" value="{{log.encryptedKey}}"/>                                                
                                                    </span>
                                                </td>
                                            </security:authorize>
                                            <td style="width: 60%; word-wrap: break-word">
                                                <table class="log-hours-table">
                                                    <thead>
                                                        <tr>
                                                            <th class="text-center" colspan="4">LOG DETAILS</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <td>
                                                                <span class="glyphicon glyphicon-stats"></span> Company
                                                            </td>
                                                            <td>{{log.company}}</td>
                                                            <td>
                                                                <span class="glyphicon glyphicon-plane"></span> Location
                                                            </td>
                                                            <td>{{log.location}}</td>
                                                        </tr>

                                                        <tr>
                                                            <td>
                                                                <span class="glyphicon glyphicon-time"></span> Start
                                                            </td>
                                                            <td>{{log.startDatetime}}</td>
                                                            <td>
                                                                <span class="glyphicon glyphicon-time"></span> End
                                                            </td>
                                                            <td>{{log.startDatetime}}</td>
                                                        </tr>

                                                        <tr>
                                                            <td>
                                                                <span class="glyphicon glyphicon-list-alt"></span> Total</td>
                                                            <td colspan="3">{{log.totalHours}}</td>
                                                        </tr>
                                                        <tr>
                                                            <td>
                                                                <span class="glyphicon glyphicon-pencil"></span> Remarks
                                                            </td>
                                                            <td colspan="3">{{log.remarks}}</td>
                                                        </tr>
                                                    </tbody>
                                                </table>                                                
                                            </td>
                                            <td style="width: 30%">
                                                <table class="log-hours-table">
                                                    <thead>
                                                        <tr>
                                                            <th class="text-center" colspan="4">PAYMENT DETAILS</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <td style="width: 30%">
                                                                <span class="glyphicon glyphicon-edit"></span> Status
                                                            </td>
                                                            <td>
                                                                {{log.strLogStatus}}
                                                            </td>
                                                        </tr>
                                                        <tr class="ng-hide" ng-show="{{log.logStatus == 'P'}}">
                                                            <td style="width: 30%">
                                                                <span class="glyphicon glyphicon-saved"></span> Paid On
                                                            </td>
                                                            <td>
                                                                {{log.createdDate}}
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <security:authorize access="hasAnyRole('ROLE_ADMIN', 'ROLE_SUPER_ADMIN')">
                <hr>
                <div class="row">
                    <div class="col-md-12 text-right">
                        <button class="btn btn-success btn-sm" ng-click="pay()">PAY SELECTED HOURS</button>
                        |
                        <button class="btn btn-danger btn-sm" ng-click="cancel()">CANCEL</button>
                        <security:authorize access="hasRole('ROLE_SUPER_ADMIN')">
                            |
                            <button class="btn btn-danger btn-sm" ng-click="delete()">DELETE</button>
                        </security:authorize>
                    </div>
                </div>   
            </security:authorize>
        </div>    
    </div>

    <div class="modal fade" id="paymentModal" tabindex="-1" role="dialog" aria-labelledby="paymentModalLabel" aria-hidden="true">
        <input type="text" name="actionType"/>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h5 class="modal-title" id="paymentModalLabel"></h5>
                </div>
                <div class="modal-body">
                    <p id="promptMessage"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">CANCEL</button>
                    <button type="button" class="btn btn-primary btn-sm" ng-click="confirm()">YES</button>
                </div>
            </div>
        </div>
    </div>
</div>